language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv sync --dev
  - pipenv shell
script:
  - py.test
  - flake8
after_success:
  - coveralls
