language: python
python:
  - "3.6"
cache: pip
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run py.test
  - pipenv run flake8
  - pipenv run black
after_success:
  - pipenv run coveralls
