language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run py.test
  - pipenv run flake8
after_success:
  - pipenv run coveralls
